### ISSUE TITLE
Pré-cadastro Empresa

### ISSUE THREAD

**Issue by piresbruna** [EquipeWeCode/estagiei-backend#60]
"Como Empresa, eu quero solicitar um cadastro no site para poder ofertar vagas de estágio."

**Critérios de Aceitação:**
- [x] Campos Obrigatórios: CNPJ, Razão Social, Nome Fantasia, Endereço, E-mail, Senha
- [x] A senha deve ser salva criptografada
- [x] Cadastro com status INATIVO
