### ISSUE TITLE
Cadastro Estudante

### ISSUE THREAD

**Issue by piresbruna** [EquipeWeCode/estagiei-backend#65]
"Como Estudante, eu quero me cadastrar para ter acesso ao site e as recomendações de Vagas."

**Critérios de Aceitação:**
- [x] Campos Obrigatórios: Nome, CPF, RG, Endereço, Histórico Escolar, Contato, E-mail, Senha
- [x]  O campo de data deve estar no padrão yyyy-mm-dd
- [ ] O campo de CPF deve estar válido
- [ ] Campos Opcionais: Competências, Histórico de Experiência
- [ ] Senha deve ser salva criptografada
